# Generated by Django 4.0.4 on 2022-04-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCartApp', '0002_item_alter_cart_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
