# Generated by Django 4.0.4 on 2022-04-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCartApp', '0005_rename_checked_out_cart_complete_remove_cart_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
    ]
